//! Reflection over the config and IR types (tests, feature `facet`): the commented
//! default config, and JSON Schema / TypeScript types for config files and
//! for `--emit-ir` output. Parsing never goes through here; it's all serde,
//! and `tests/reflect.rs` checks the two agree.
//!
//! The outputs are checked in (`config.default.yaml` / `.json`, `config.schema.json`,
//! `ir.schema.json`, `ts/src/generated/*.ts`) and kept current by
//! `UPDATE_GOLDEN=1 cargo test --features facet` (see `tests`).

mod doc;
mod schema;
#[cfg(test)]
mod tests;
mod yaml;

use anyhow::{Result, anyhow};
use facet::Facet;
use serde_json::json;

use crate::config::Config;
use crate::ts::export::Export;

/// [`Config::default`] as commented YAML: `config.default.yaml`.
pub fn example_config() -> Result<String> {
    let options = yaml::SerializeOptions {
        header: vec!["yaml-language-server: $schema=./config.schema.json".to_string()],
        ..yaml::SerializeOptions::default()
    };
    yaml::to_string(&Config::default(), &options).map_err(|e| anyhow!("{e}"))
}

pub fn example_config_json() -> Result<String> {
    serde_json::to_string_pretty(&Config::default()).map_err(|e| anyhow!("{e}"))
}

/// Any config as YAML (with docs), e.g. to round-trip it.
pub fn to_yaml(config: &Config) -> Result<String> {
    yaml::to_string(config, &yaml::SerializeOptions::default()).map_err(|e| anyhow!("{e}"))
}

/// JSON Schema for config files, e.g. for editor completion.
pub fn config_schema() -> Result<String> {
    // Read from a number or a string (a hand-written `Deserialize`).
    let status = json!({
        "anyOf": [{ "type": "integer" }, { "type": "string" }],
        "description": "`200`, `2xx` or `default`.",
    });
    to_json(schema::schema_for(
        Config::SHAPE,
        &[("StatusPattern", status)],
    ))
}

/// JSON Schema for `--emit-ir` output.
pub fn ir_schema() -> Result<String> {
    // Serialised as the value itself (`null` for `Null`), which reflection
    // can't see through the untagged enum.
    let literal = json!({
        "type": ["string", "number", "boolean", "null"],
        "description": "A `const` / `enum` value.",
    });
    to_json(schema::schema_for(Export::SHAPE, &[("Literal", literal)]))
}

/// TypeScript types for config files (`Config` and what it contains).
pub fn config_typescript() -> String {
    typescript::<Config>(&[])
}

/// TypeScript types for `--emit-ir` output (`Export` and what it
/// contains).
pub fn ir_typescript() -> String {
    typescript::<Export>(&[("Literal", "string | number | boolean | null")])
}

/// `overrides` replaces the bodies of the named type aliases, for ones whose
/// serde form reflection can't see (as [`schema::schema_for`]'s do).
fn typescript<T: Facet<'static>>(overrides: &[(&str, &str)]) -> String {
    let mut generator = facet_typescript::TypeScriptGenerator::new();
    generator.add_type::<T>();
    // Doc lines (` * text`) are written as-is, so a `*/` in them (`**/x`)
    // would end the comment.
    let code: Vec<_> = generator
        .finish()
        .lines()
        .map(|line| match line.trim_start().strip_prefix("* ") {
            Some(_) => line.replace("*/", "*\\/"),
            None => override_alias(line, overrides).unwrap_or_else(|| index_signatures(line)),
        })
        .collect();
    format!(
        "// Generated by opi from its Rust types. Do not edit.\n\n{}\n",
        code.join("\n")
    )
}

/// `export type Literal = ...;` -> the override's body, if there is one.
fn override_alias(line: &str, overrides: &[(&str, &str)]) -> Option<String> {
    let rest = line.strip_prefix("export type ")?;
    let (name, _) = rest.split_once(" = ")?;
    let (_, body) = overrides.iter().find(|(n, _)| *n == name)?;
    Some(format!("export type {name} = {body};"))
}

/// `Record<string, Shape>` -> `{ [key: string]: Shape }`: the same type,
/// but TS only accepts the latter in a recursive alias
/// (`type Shape = Value | Record<string, Shape>` is "circular").
fn index_signatures(line: &str) -> String {
    const RECORD: &str = "Record<string, ";
    let mut out = String::new();
    let mut rest = line;
    while let Some(start) = rest.find(RECORD) {
        let after = &rest[start + RECORD.len()..];
        let name_len = after
            .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
            .unwrap_or(after.len());
        if name_len == 0 || !after[name_len..].starts_with('>') {
            out.push_str(&rest[..start + RECORD.len()]);
            rest = after;
            continue;
        }
        out.push_str(&rest[..start]);
        out.push_str(&format!("{{ [key: string]: {} }}", &after[..name_len]));
        rest = &after[name_len + 1..];
    }
    out.push_str(rest);
    out
}

fn to_json(schema: serde_json::Value) -> Result<String> {
    Ok(serde_json::to_string_pretty(&schema)? + "\n")
}
