// This file is generated by opi. Do not edit.

/** @description A reusable component */
export type Component = {
  type: 'component'
  /** @description Server-assigned id */
  readonly id?: string
  component: Record<string, unknown>
  tags?: string[] | null
}
export type Mixed = (string | 1 | -2 | null)[]
/** @summary List items */
export type GetShopItems = {
  method: 'GET'
  path: '/shop/items'
  request: {
    body?: never
    contentType?: never
    params?: never
    query?: {
      limit?: number
    }
    headers?: never
    cookies?: never
  }
  response: {
    'application/json': {
      /** @description The items */
      200: Component[]
    }
  }
}
/** @deprecated */
export type PostShopItems = {
  method: 'POST'
  path: '/shop/items'
  request: {
    body: Component
    contentType: 'application/json'
    params?: never
    query?: never
    headers?: never
    cookies?: never
  }
  response: {
    none: {
      /** @description Created */
      201: never
    }
  }
}
export interface Paths {
  '/shop/items': {
    /** @summary List items */
    get: GetShopItems
    /** @deprecated */
    post: PostShopItems
  }
}
