// This file is generated by opi. Do not edit.

/** @description A reusable component */
export type Component = {
	type: "component";
	/** @description Server-assigned id */
	readonly id?: string;
	component: Record<string, unknown>;
	tags?: string[] | null;
};
export type Error2 = {
	type: "error";
	message: string;
};
/** @summary Fetch a component */
export type GetComponentsByName = {
	method: "GET";
	path: "/components/{name}";
	request: {
		body?: never;
		contentType?: never;
		params: {
			name: string;
		};
		query?: never;
		headers?: never;
		cookies?: never;
	};
	response: {
		/** @description The component */
		status: 200;
		contentType: "application/json";
		body: Component;
	} | {
		/** @description Missing or wrong token */
		status: 401;
		contentType: "application/json";
		body: Error2;
	} | {
		/** @description No such component */
		status: 404;
		contentType: "application/json";
		body: Error2;
	};
};
export type PutComponentsByName = {
	method: "PUT";
	path: "/components/{name}";
	request: {
		body: Component;
		contentType: "application/json";
		params: {
			name: string;
		};
		query?: {
			"dry-run"?: boolean;
		};
		headers: {
			"X-Request-Id": string;
		};
		cookies?: never;
	} | {
		body: Blob;
		contentType: "application/octet-stream";
		params: {
			name: string;
		};
		query?: {
			"dry-run"?: boolean;
		};
		headers: {
			"X-Request-Id": string;
		};
		cookies?: never;
	};
	response: {
		/** @description Saved */
		status: 204;
		contentType: null;
		body?: never;
	} | {
		/** @description Unexpected error */
		status: "default";
		contentType: "application/json";
		body: Error2;
	};
};
/** @summary List items */
export type GetShopItems = {
	method: "GET";
	path: "/shop/items";
	request: {
		body?: never;
		contentType?: never;
		params?: never;
		query?: {
			limit?: number;
		};
		headers?: never;
		cookies?: never;
	};
	response: {
		/** @description The items */
		status: 200;
		contentType: "application/json";
		body: Component[];
	};
};
/** @deprecated */
export type PostShopItems = {
	method: "POST";
	path: "/shop/items";
	request: {
		body: Component;
		contentType: "application/json";
		params?: never;
		query?: never;
		headers?: never;
		cookies?: never;
	};
	response: {
		/** @description Created */
		status: 201;
		contentType: null;
		body?: never;
	};
};
/** @description Every GET operation. */
export type GetRequests = GetComponentsByName | GetShopItems;
export type ComponentsRoutes = {
	/** @summary Fetch a component */
	"GET /components/{name}": GetComponentsByName;
	"PUT /components/{name}": PutComponentsByName;
};
export type AdminRoutes = {
	"PUT /components/{name}": PutComponentsByName;
	/** @deprecated */
	"POST /shop/items": PostShopItems;
};
export type ShopRoutes = {
	/** @summary List items */
	"GET /shop/items": GetShopItems;
	/** @deprecated */
	"POST /shop/items": PostShopItems;
};
export type ShopPaths = {
	"/shop/items": {
		/** @summary List items */
		get: GetShopItems;
		/** @deprecated */
		post: PostShopItems;
	};
};
export type RequestBodies = {
	/** @deprecated */
	createItem: Pick<PostShopItems["request"], "body">;
};
export type ByTag = {
	components: GetComponentsByName | PutComponentsByName;
	admin: PutComponentsByName | PostShopItems;
	shop: GetShopItems | PostShopItems;
};
export type GETOps = {
	/** @summary Fetch a component */
	"/components/{name}": {
		request: GetComponentsByName["request"];
		response: GetComponentsByName["response"];
	};
	/** @summary List items */
	"/shop/items": {
		request: GetShopItems["request"];
		response: GetShopItems["response"];
	};
};
export type PUTOps = {
	"/components/{name}": {
		request: PutComponentsByName["request"];
		response: PutComponentsByName["response"];
	};
};
export type POSTOps = {
	/** @deprecated */
	"/shop/items": {
		request: PostShopItems["request"];
		response: PostShopItems["response"];
	};
};
export type JsonOps = {
	"PUT /components/{name}": {
		request: PutComponentsByName["request"];
		response: Extract<PutComponentsByName["response"], {
			contentType: "application/json";
		}>;
	};
	/** @deprecated */
	"POST /shop/items": {
		request: PostShopItems["request"];
		response: never;
	};
};
export type ApplicationJsonOps = {
	"/components/{name}": {
		method: PutComponentsByName["method"];
		request: Pick<Extract<PutComponentsByName["request"], {
			contentType: "application/json";
		}>, "body" | "query" | "params">;
		response: Extract<PutComponentsByName["response"], {
			contentType: "application/json";
		}>;
	};
	/** @deprecated */
	"/shop/items": {
		method: PostShopItems["method"];
		request: Pick<PostShopItems["request"], "body" | "query" | "params">;
		response: never;
	};
};
export type ApplicationOctetStreamOps = {
	"/components/{name}": {
		method: PutComponentsByName["method"];
		request: Pick<Extract<PutComponentsByName["request"], {
			contentType: "application/octet-stream";
		}>, "body" | "query" | "params">;
		response: Extract<PutComponentsByName["response"], {
			contentType: "application/json";
		}>;
	};
};
export type ComponentsUnion = GetComponentsByName | PutComponentsByName;
export type AdminUnion = PutComponentsByName;
export type ShopUnion = GetShopItems;
export type Errors = {
	/** @summary Fetch a component */
	"GET /components/{name}": Pick<Extract<GetComponentsByName["response"], {
		status: 401 | 404;
	}>, "status" | "body">;
	"PUT /components/{name}": Pick<Extract<PutComponentsByName["response"], {
		contentType: "application/json";
	}>, "status" | "body">;
};
export type Bodies = {
	/** @summary Fetch a component */
	"GET /components/{name}": {
		200: Extract<GetComponentsByName["response"], {
			status: 200;
		}>["body"];
		401: Extract<GetComponentsByName["response"], {
			status: 401;
		}>["body"];
		404: Extract<GetComponentsByName["response"], {
			status: 404;
		}>["body"];
	};
	"PUT /components/{name}": {
		204: Extract<PutComponentsByName["response"], {
			status: 204;
		}>["body"];
		default: Extract<PutComponentsByName["response"], {
			status: "default";
		}>["body"];
	};
	/** @summary List items */
	"GET /shop/items": {
		200: GetShopItems["response"]["body"];
	};
	/** @deprecated */
	"POST /shop/items": {
		201: PostShopItems["response"]["body"];
	};
};
export type Summaries = {
	/** @summary Fetch a component */
	GetComponentsByName: "Fetch a component";
	/** @summary List items */
	GetShopItems: "List items";
};
