// This file is generated by opi. Do not edit.

export type Item = {
  id: number
  kind: 'item'
  name?: string | null
  tags?: string[]
  /** @description A `$ref` with a sibling description (3.1+) */
  parent?: Item
  anything?: unknown
  nothing?: never
  either?: string | number
  nothingButNull?: null
  thumbnail?: string
  packed?: string
}
export type Update = {
  id: number
}
export type QuerySearch = {
  method: 'QUERY'
  path: '/search'
  request: {
    body?: never
    contentType?: never
    params?: never
    query: {
      q: string
      limit?: number
    }
    headers?: never
    cookies?: never
  }
  response: {
    'application/json': {
      200: Item[]
    }
  }
}
export type PurgeSearch = {
  method: 'PURGE'
  path: '/search'
  request: {
    body?: never
    contentType?: never
    params?: never
    query?: never
    headers?: never
    cookies?: never
  }
  response: {
    none: {
      /** @description Purged */
      204: never
    }
  }
}
export type GetEvents = {
  method: 'GET'
  path: '/events'
  request: {
    body?: never
    contentType?: never
    params?: never
    query?: never
    headers?: never
    cookies?: never
  }
  response: {
    'text/event-stream': {
      /**
       * @description One event per message
       * @stream
       */
      '2XX': {
        event?: 'update'
        /** @contentMediaType application/json */
        data: Update
      }
    }
  }
}
export interface Paths {
  '/search': {
    query: QuerySearch
    purge: PurgeSearch
  }
  '/events': {
    get: GetEvents
  }
}
